# Note: This does not currently work
version: '2'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=names
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      - customer-network
  customer:
    image: murphye/customer-service:latest
    ports:
      - '8081:8080'
    networks:
      - customer-network
  person:
    image: murphye/person-service:latest
    ports:
      - '8082:8080'
    networks:
      - customer-network
  name:
    image: murphye/name-service:latest
    ports:
      - '8083:8080'
    depends_on:
      - postgres
    networks:
      - customer-network
networks:
  customer-network:
    driver: bridge