apiVersion: v1
kind: ServiceAccount
metadata:
  name: person
---
apiVersion: v1
kind: Service
metadata:
  name: person
  labels:
    app: person
    service: person
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: person
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
spec:
  replicas: 3
  selector:
    matchLabels:
      app: person
      version: v1
  template:
    metadata:
      labels:
        app: person
        version: v1
      annotations:
        sidecar.istio.io/userVolumeMount: '[{"name": "netty-sockets", "mountPath": "/var/run/netty"}]'
        sidecar.istio.io/proxyCPULimit: "3"
        sidecar.istio.io/proxyMemoryLimit: "3Gi"
    spec:
      serviceAccountName: person
      containers:
      - image: docker.io/murphye/person-service:latest
        name: person
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/run/netty
            name: netty-sockets
      volumes:
      - name: netty-sockets
        emptyDir: {}
      securityContext:
        fsGroup: 1337