apiVersion: v1
kind: ServiceAccount
metadata:
  name: name
---
apiVersion: v1
kind: Service
metadata:
  name: name
  labels:
    app: name
    service: name
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: name
      version: v1
  template:
    metadata:
      labels:
        app: name
        version: v1
      annotations:
        sidecar.istio.io/userVolumeMount: '[{"name": "name-socket", "mountPath": "/var/run/name"}]'
        sidecar.istio.io/proxyCPULimit: "3"
        sidecar.istio.io/proxyMemoryLimit: "3Gi"
    spec:
      serviceAccountName: name
      containers:
      - image: docker.io/murphye/name-service:latest
        name: name
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/run/name
            name: name-socket
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - postgres
            topologyKey: "kubernetes.io/hostname"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - customer
                - person
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: name-socket
        emptyDir: {}
      securityContext:
        fsGroup: 1337